using System.Globalization;
using System.Text;
using CuBlocky.Server.Models;

namespace CuBlocky.Server.Compiler;

// Emits C# registration calls from form-driven content + block behavior.
// Targets .NET Framework 4.7.2 (BepInEx 5 / Unity / Mono).
public static class CodeEmitter
{
    public static string EmitRegisterContent(Blueprint bp, List<ItemEntry> extraItems = null, List<RecipeEntry> extraRecipes = null, List<BuildingEntry> buildings = null, List<TileEntry> tiles = null, List<LocaleEntry> locales = null, List<LiquidEntry> liquids = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by CuBlocky. Do not edit by hand; edit the .cbp and recompile.");
        sb.AppendLine("// Depends on CUCoreLib (net.cucorelib). Place CUCoreLib.dll in BepInEx/plugins/.");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CUCoreLib.Helpers;");
        sb.AppendLine("using CUCoreLib.Registries;");
        sb.AppendLine("using CUCoreLib.Data;");
        sb.AppendLine("using HarmonyLib;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine($"namespace {SafeIdent(bp.Mod.RootNamespace)}");
        sb.AppendLine("{");
        sb.AppendLine("    public static class RegisterContent");
        sb.AppendLine("    {");
        sb.AppendLine("        // Magazine configs: itemId -> (ammoType, maxRounds, startRounds)");
        sb.AppendLine("        public static readonly Dictionary<string, (string ammoType, int maxRounds, int startRounds)> _magazineConfigs = new Dictionary<string, (string, int, int)>();");
        sb.AppendLine();
        sb.AppendLine("        // Start condition configs: itemId -> initialCondition");
        sb.AppendLine("        public static readonly Dictionary<string, float> _startConditionConfigs = new Dictionary<string, float>();");
        sb.AppendLine();
        sb.AppendLine("        private static bool _debugSprite = true;");
        sb.AppendLine("        private static readonly System.Text.StringBuilder _spriteLog = new System.Text.StringBuilder();");
        sb.AppendLine("        private static Sprite _loadSprite(string name)");
        sb.AppendLine("        {");
        sb.AppendLine("            var asm = typeof(RegisterContent).Assembly;");
        sb.AppendLine("            var names = asm.GetManifestResourceNames();");
        sb.AppendLine("            bool found = names.Any(n => n.EndsWith(name) || n.Contains(name));");
        sb.AppendLine("            _spriteLog.AppendLine($\"Sprite '{{name}}' -> embedded={{found}} resources=[{{string.Join(\",\", names)}}]\");");
        sb.AppendLine("            var sprite = AssetLoader.LoadEmbeddedSprite(name);");
        sb.AppendLine("            _spriteLog.AppendLine($\"  -> result={{(sprite != null ? \"OK\" : \"NULL\")}}\");");
        sb.AppendLine("            return sprite;");
        sb.AppendLine("        }");
        sb.AppendLine("        private static AudioClip _loadAudio(string name)");
        sb.AppendLine("        {");
        sb.AppendLine("            var asm = typeof(RegisterContent).Assembly;");
        sb.AppendLine("            var names = asm.GetManifestResourceNames();");
        sb.AppendLine("            bool found = names.Any(n => n.EndsWith(name) || n.Contains(name));");
        sb.AppendLine("            _spriteLog.AppendLine($\"Audio '{{name}}' -> embedded={{found}} resources=[{{string.Join(\",\", names)}}]\");");
        sb.AppendLine("            var clip = AssetLoader.LoadEmbeddedAudio(name);");
        sb.AppendLine("            _spriteLog.AppendLine($\"  -> result={{(clip != null ? \"OK\" : \"NULL\")}}\");");
        sb.AppendLine("            return clip;");
        sb.AppendLine("        }");
        sb.AppendLine("        private static Sprite LoadSprite(string name) => _loadSprite(name);");
        sb.AppendLine("        private static AudioClip LoadAudio(string name) => _loadAudio(name);");
        sb.AppendLine("        private static void DumpSpriteLog()");
        sb.AppendLine("        {");
        sb.AppendLine("            Plugin.Logger.LogInfo($\"[CuBlocky] Sprite/Audio debug log:\\n{{_spriteLog}}\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public static void RegisterAll()");
        sb.AppendLine("        {");

        // Emit liquids first (items may reference them)
        if (liquids != null)
        {
            foreach (var l in liquids)
                sb.Append(EmitLiquid(l));
        }

        var allItems = new List<ItemEntry>(bp.Items);
        if (extraItems != null) allItems.AddRange(extraItems);
        foreach (var item in allItems)
            sb.Append(EmitItem(item, bp));

        var allRecipes = new List<RecipeEntry>(bp.Recipes);
        if (extraRecipes != null) allRecipes.AddRange(extraRecipes);
        foreach (var recipe in allRecipes)
            sb.Append(EmitRecipe(recipe));

        if (buildings != null)
        {
            foreach (var b in buildings)
                sb.Append(EmitBuilding(b));
        }

        if (tiles != null)
        {
            foreach (var t in tiles)
                sb.Append(EmitTile(t));
        }

        if (locales != null)
        {
            foreach (var l in locales)
                sb.Append(EmitLocale(l));
        }

        sb.AppendLine("        DumpSpriteLog();");
        sb.AppendLine("        }");
        var allItemsList = new List<ItemEntry>(bp.Items);
        if (extraItems != null) allItemsList.AddRange(extraItems);
        if (allItemsList.Any(it => string.IsNullOrEmpty(it.SpriteAssetId)))
            sb.AppendLine(EmitPlaceholderSpriteHelper());

        // Emit magazine Harmony patch
        sb.AppendLine();
        sb.AppendLine("        // Harmony patch to apply AmmoScript to magazine items at runtime");
        sb.AppendLine("        [HarmonyPatch(typeof(Item), \"Start\")]");
        sb.AppendLine("        [HarmonyPostfix]");
        sb.AppendLine("        public static void ApplyMagazineComponents(Item __instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (__instance == null || string.IsNullOrEmpty(__instance.id)) return;");
        sb.AppendLine("            if (!_magazineConfigs.TryGetValue(__instance.id, out var cfg)) return;");
        sb.AppendLine("            var ammo = __instance.GetComponent<AmmoScript>();");
        sb.AppendLine("            if (ammo == null) ammo = __instance.gameObject.AddComponent<AmmoScript>();");
        sb.AppendLine("            ammo.itemType = AmmoScript.AmmoItemType.Magazine;");
        sb.AppendLine("            switch (cfg.ammoType) {");
        sb.AppendLine("                case \"Pistol\": ammo.ammoType = GunScript.AmmoType.Pistol; break;");
        sb.AppendLine("                case \"Rifle\": ammo.ammoType = GunScript.AmmoType.Rifle; break;");
        sb.AppendLine("                case \"Shotgun\": ammo.ammoType = GunScript.AmmoType.Shotgun; break;");
        sb.AppendLine("                default: ammo.ammoType = GunScript.AmmoType.Pistol; break;");
        sb.AppendLine("            }");
        sb.AppendLine("            ammo.maxRounds = Mathf.Max(1, cfg.maxRounds);");
        sb.AppendLine("            ammo.rounds = Mathf.Clamp(cfg.startRounds, 0, ammo.maxRounds);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Harmony patch to apply initial condition at runtime");
        sb.AppendLine("        [HarmonyPatch(typeof(Item), \"Start\")]");
        sb.AppendLine("        [HarmonyPostfix]");
        sb.AppendLine("        public static void ApplyStartCondition(Item __instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (__instance == null || string.IsNullOrEmpty(__instance.id)) return;");
        sb.AppendLine("            if (!_startConditionConfigs.TryGetValue(__instance.id, out var cond)) return;");
        sb.AppendLine("            __instance.condition = Mathf.Clamp01(cond);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitItem(ItemEntry it, Blueprint bp)
    {
        var sb = new StringBuilder();
        sb.AppendLine("            // Item: " + it.Id);
        sb.Append($"            ItemRegistry.Register(");
        sb.Append($"\"{Escape(it.Id)}\", ");
        var infoType = it.IsAdvanced ? "CustomItemInfo" : "ItemInfo";
        sb.AppendLine($"new {infoType}");
        sb.AppendLine("            {");
        sb.AppendLine($"                fullName = \"{Escape(it.FullName)}\",");
        sb.AppendLine($"                description = \"{Escape(it.Description)}\",");
        sb.AppendLine($"                category = \"{Escape(it.Category)}\",");
        sb.AppendLine($"                weight = {F(it.Weight)}f,");
        sb.AppendLine($"                value = {it.Value},");
        if (it.Usable || !string.IsNullOrEmpty(it.UseAction))
            sb.AppendLine($"                usable = true,");
        if (it.UsableOnLimb || !string.IsNullOrEmpty(it.UseLimbAction))
            sb.AppendLine($"                usableOnLimb = true,");
        sb.AppendLine($"                decayMinutes = {F(it.DecayMinutes)}f,");
        if (!string.IsNullOrEmpty(it.Tags))
            sb.AppendLine($"                tags = \"{Escape(it.Tags)}\",");
        sb.AppendLine($"                rec = new Recognition({it.Recognition}),");

        // Advanced: Container
        if (it.Container != null)
        {
            sb.AppendLine($"                Container = new ContainerProperties");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Capacity = {it.Container.Capacity}f,");
            sb.AppendLine($"                    MaxWeightPerItem = {it.Container.MaxWeightPerItem}f,");
            sb.AppendLine($"                    EncumbranceReduction = {it.Container.EncumbranceReduction}f,");
            sb.AppendLine($"                    ItemsVisible = {B(it.Container.ItemsVisible)},");
            if (!string.IsNullOrEmpty(it.Container.TagRestriction))
                sb.AppendLine($"                    TagRestriction = new string[]{{\"{Escape(it.Container.TagRestriction)}\"}},");
            sb.AppendLine("                },");
        }

        // Advanced: Tool
        if (it.Tool != null)
        {
            sb.AppendLine($"                Tool = new ToolProperties");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Damage = {it.Tool.Damage}f,");
            sb.AppendLine($"                    StructuralDamage = {it.Tool.StructuralDamage}f,");
            sb.AppendLine($"                    Distance = {it.Tool.Distance}f,");
            sb.AppendLine($"                    KnockBack = {it.Tool.KnockBack}f,");
            sb.AppendLine($"                    Cooldown = {it.Tool.Cooldown}f,");
            sb.AppendLine($"                    StaminaUse = {it.Tool.StaminaUse}f,");
            sb.AppendLine($"                    Piercing = {B(it.Tool.Piercing)},");
            sb.AppendLine("                },");
        }

        // Advanced: Wearable
        if (it.Wearable != null)
        {
            sb.AppendLine($"                wearable = true,");
            sb.AppendLine($"                desiredWearLimb = \"{Escape(it.Wearable.DesiredWearLimb)}\",");
            sb.AppendLine($"                wearSlotId = \"{Escape(it.Wearable.WearSlotId)}\",");
            sb.AppendLine($"                wearableArmor = {it.Wearable.WearableArmor}f,");
            sb.AppendLine($"                wearableIsolation = {it.Wearable.WearableIsolation}f,");
            sb.AppendLine($"                wearableHitDurabilityLossMultiplier = {it.Wearable.WearableHitDurabilityLossMultiplier}f,");
        }

        // Advanced: LiquidContainer
        if (it.LiquidContainer != null)
        {
            sb.AppendLine($"                capacity = {it.LiquidContainer.Capacity}f,");
            sb.AppendLine($"                autoFill = {B(it.LiquidContainer.AutoFill)},");
            sb.AppendLine($"                defaultContents = new List<LiquidStack>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    new LiquidStack(\"{Escape(it.LiquidContainer.LiquidId)}\", {it.LiquidContainer.LiquidAmount}f),");
            sb.AppendLine("                },");
        }

        // Advanced: Battery
        if (it.Battery != null)
        {
            sb.AppendLine($"                Battery = new BatteryProperties");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Preset = BatteryItem.BatteryPreset.{it.Battery.Preset},");
            sb.AppendLine($"                    StartCharge = {it.Battery.StartCharge}f,");
            sb.AppendLine($"                    SpawnWithBattery = {B(it.Battery.SpawnWithBattery)},");
            sb.AppendLine("                },");
        }

        // Advanced: Light
        if (it.Light != null)
        {
            sb.AppendLine($"                Light = new LightProperties");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Intensity = {it.Light.Intensity}f,");
            sb.AppendLine($"                    PointLightOuterRadius = {it.Light.Radius}f,");
            sb.AppendLine($"                    Color = new Color({it.Light.ColorR}f, {it.Light.ColorG}f, {it.Light.ColorB}f),");
            sb.AppendLine($"                    LightType = CustomLightType.Point,");
            sb.AppendLine("                },");
        }

        // Advanced: Bandage
        if (it.Bandage != null)
        {
            sb.AppendLine($"                Bandage = new BandageProperties");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Effectiveness = {it.Bandage.Effectiveness}f,");
            sb.AppendLine($"                    SkinHealAmount = {it.Bandage.SkinHealAmount}f,");
            sb.AppendLine($"                    BandageSlowAmount = {it.Bandage.BandageSlowAmount}f,");
            sb.AppendLine($"                    PainReduction = {it.Bandage.PainReduction}f,");
            sb.AppendLine($"                    BoneHealTimerReduction = {it.Bandage.BoneHealTimerReduction}f,");
            sb.AppendLine($"                    DislocationTimerReduction = {it.Bandage.DislocationTimerReduction}f,");
            sb.AppendLine("                },");
        }

        // Advanced: Syringe
        if (it.Syringe != null)
        {
            sb.AppendLine($"                Syringe = new SyringeProperties");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Capacity = {it.Syringe.Capacity}f,");
            sb.AppendLine($"                    AmountPerFullUse = {it.Syringe.AmountPerFullUse}f,");
            sb.AppendLine($"                    AutoFill = {B(it.Syringe.AutoFill)},");
            sb.AppendLine($"                    DefaultContents = new List<LiquidStack>");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        new LiquidStack(\"{Escape(it.Syringe.LiquidId)}\", {it.Syringe.LiquidAmount}f),");
            sb.AppendLine("                    },");
            sb.AppendLine("                },");
        }

        // Advanced: Gun
        if (it.Gun != null)
        {
            sb.AppendLine($"                Gun = new GunProperties");
            sb.AppendLine("                {");
            sb.AppendLine($"                    AmmoType = GunScript.AmmoType.{it.Gun.AmmoType},");
            sb.AppendLine($"                    FiringMode = GunScript.FiringMode.{it.Gun.FiringMode},");
            sb.AppendLine($"                    FeedType = GunScript.FeedType.{it.Gun.FeedType},");
            sb.AppendLine($"                    MagCapacity = {it.Gun.MagCapacity},");
            sb.AppendLine($"                    KnockBack = {it.Gun.KnockBack}f,");
            sb.AppendLine($"                    StructureDamage = {it.Gun.StructureDamage}f,");
            sb.AppendLine($"                    AnimalDamage = {it.Gun.AnimalDamage}f,");
            sb.AppendLine($"                    Loudness = {it.Gun.Loudness}f,");
            sb.AppendLine($"                    DesiredGasTime = {it.Gun.DesiredGasTime}f,");
            sb.AppendLine($"                    ShotsPerFire = {it.Gun.ShotsPerFire},");
            sb.AppendLine($"                    VerticalSpread = {it.Gun.VerticalSpread}f,");
            sb.AppendLine($"                    ConditionLossPerShot = {it.Gun.ConditionLossPerShot}f,");
            if (!string.IsNullOrEmpty(it.Gun.RackedSprite))
                sb.AppendLine($"                    RackedSprite = LoadSprite(\"{Escape(CleanSpriteName(it.Gun.RackedSprite))}\"),");
            if (!string.IsNullOrEmpty(it.Gun.NormalSpriteNoMag))
                sb.AppendLine($"                    NormalSpriteNoMag = LoadSprite(\"{Escape(CleanSpriteName(it.Gun.NormalSpriteNoMag))}\"),");
            if (!string.IsNullOrEmpty(it.Gun.RackedSpriteNoMag))
                sb.AppendLine($"                    RackedSpriteNoMag = LoadSprite(\"{Escape(CleanSpriteName(it.Gun.RackedSpriteNoMag))}\"),");
            if (!string.IsNullOrEmpty(it.Gun.FireSound))
                sb.AppendLine($"                    FireSound = LoadAudio(\"{Escape(CleanSpriteName(it.Gun.FireSound))}\"),");
            if (!string.IsNullOrEmpty(it.Gun.CustomRack))
                sb.AppendLine($"                    CustomRack = LoadAudio(\"{Escape(CleanSpriteName(it.Gun.CustomRack))}\"),");
            if (!string.IsNullOrEmpty(it.Gun.CustomUnrack))
                sb.AppendLine($"                    CustomUnrack = LoadAudio(\"{Escape(CleanSpriteName(it.Gun.CustomUnrack))}\"),");
            sb.AppendLine("                },");
            sb.AppendLine($"                slotRotation = -90f,");
        }

        // Advanced: Magazine (stored in static dict, applied via Harmony patch)
        // NOTE: must be outside ItemRegistry.Register() call

        // useAction from Blockly-generated C# code
        if (!string.IsNullOrEmpty(it.UseAction))
        {
            sb.AppendLine("                useAction = (body, item) =>");
            sb.AppendLine("                {");
            // Replace {body} and {item} placeholders with actual parameter names
            var code = it.UseAction
                .Replace("{body}", "body")
                .Replace("{item}", "item")
                .Replace("{limb}", "limb");
            foreach (var line in code.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                if (!string.IsNullOrWhiteSpace(trimmed))
                    sb.AppendLine("                    " + trimmed);
            }
            sb.AppendLine("                },");
        }

        // useLimbAction from Blockly-generated C# code
        if (!string.IsNullOrEmpty(it.UseLimbAction))
        {
            sb.AppendLine("                useLimbAction = (limb, item) =>");
            sb.AppendLine("                {");
            var code = it.UseLimbAction
                .Replace("{body}", "limb")
                .Replace("{item}", "item")
                .Replace("{limb}", "limb");
            foreach (var line in code.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                if (!string.IsNullOrWhiteSpace(trimmed))
                    sb.AppendLine("                    " + trimmed);
            }
            sb.AppendLine("                },");
        }

        sb.AppendLine("            }");
        // sprite - load from embedded resource or generate placeholder
        if (!string.IsNullOrEmpty(it.SpriteAssetId))
        {
            var spriteName = ResolveSpriteName(it.SpriteAssetId, bp);
            if (string.IsNullOrEmpty(spriteName))
                spriteName = it.Id + ".png";
            sb.AppendLine($"            , LoadSprite(\"{Escape(CleanSpriteName(spriteName))}\")");
        }
        else
        {
            sb.AppendLine($"            , CuBlockyPlaceholderSprite(\"{Escape(it.Id)}\")");
        }
        if (it.SpawnFrequency != 1)
            sb.AppendLine($"            , {it.SpawnFrequency}");
        sb.AppendLine("            );");
        // Magazine config: stored in static dict, applied via Harmony patch on Item.Start
        if (it.Magazine != null)
        {
            sb.AppendLine($"            _magazineConfigs[\"{Escape(it.Id)}\"] = (\"{Escape(it.Magazine.AmmoType)}\", {it.Magazine.MaxRounds}, {it.Magazine.StartRounds});");
        }
        // Start condition config: stored in static dict, applied via Harmony patch on Item.Start
        if (it.StartCondition >= 0f)
        {
            sb.AppendLine($"            _startConditionConfigs[\"{Escape(it.Id)}\"] = {F(it.StartCondition)}f;");
        }
        sb.AppendLine();
        return sb.ToString();
    }

    public static string EmitLiquid(LiquidEntry l)
    {
        var sb = new StringBuilder();
        sb.AppendLine("            // Liquid: " + l.Id);
        sb.AppendLine($"            LiquidRegistry.Register(\"{Escape(l.Id)}\", new CustomLiquidInfo");
        sb.AppendLine("            {");
        sb.AppendLine($"                name = \"{Escape(l.Name)}\",");
        sb.AppendLine($"                description = \"{Escape(l.Description)}\",");
        sb.AppendLine($"                color = new Color({l.ColorR}f, {l.ColorG}f, {l.ColorB}f),");
        sb.AppendLine($"                valuePerLiter = {l.ValuePerLiter}f,");
        if (l.HealthUsable)
            sb.AppendLine($"                healthUsable = true,");
        if (l.Injectable)
            sb.AppendLine($"                injectable = true,");
        if (l.InjectionSickness != "1")
            sb.AppendLine($"                injectionSickness = {l.InjectionSickness}f,");
        if (l.Unobtainable)
            sb.AppendLine($"                unobtainable = true,");
        sb.AppendLine("            });");
        sb.AppendLine();
        return sb.ToString();
    }

    /// <summary>
    /// Emits a helper method that generates a colored placeholder sprite at runtime.
    /// Called once per RegisterContent class.
    /// </summary>
    public static string EmitPlaceholderSpriteHelper()
    {
        return @"
        private static UnityEngine.Sprite CuBlockyPlaceholderSprite(string itemId)
        {
            int size = 16;
            var tex = new UnityEngine.Texture2D(size, size, UnityEngine.TextureFormat.RGBA32, false);
            var pixels = new UnityEngine.Color[size * size];
            // Magenta background
            for (int i = 0; i < pixels.Length; i++) pixels[i] = new UnityEngine.Color(1f, 0f, 1f, 1f);
            // Dark border
            for (int x = 0; x < size; x++) { pixels[x] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); pixels[(size - 1) * size + x] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); }
            for (int y = 0; y < size; y++) { pixels[y * size] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); pixels[y * size + size - 1] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); }
            // Small cross in center
            int cx = size / 2, cy = size / 2;
            pixels[cy * size + cx] = UnityEngine.Color.white;
            pixels[cy * size + cx - 1] = UnityEngine.Color.white;
            pixels[cy * size + cx + 1] = UnityEngine.Color.white;
            pixels[(cy - 1) * size + cx] = UnityEngine.Color.white;
            pixels[(cy + 1) * size + cx] = UnityEngine.Color.white;
            tex.SetPixels(pixels);
            tex.Apply();
            return UnityEngine.Sprite.Create(tex, new UnityEngine.Rect(0, 0, size, size), new UnityEngine.Vector2(0.5f, 0.5f), 16f);
        }
";
    }

    public static string EmitRecipe(RecipeEntry r)
    {
        var sb = new StringBuilder();
        sb.AppendLine("            RecipeRegistry.Register(new Recipe");
        sb.AppendLine("            {");
        sb.AppendLine($"                INT = {r.IntRequirement},");
        sb.AppendLine($"                category = Recipes.RecipeCategory.{Cap(r.Category)},");
        sb.AppendLine("                result = new RecipeResult");
        sb.AppendLine("                {");
        sb.AppendLine($"                    id = \"{Escape(r.ResultId)}\",");
        sb.AppendLine($"                    amount = {r.ResultAmount},");
        sb.AppendLine($"                    isLiquid = {B(r.IsLiquidResult)},");
        sb.AppendLine($"                    resultCondition = {F(r.ResultCondition)}f,");
        sb.AppendLine("                },");
        sb.AppendLine("                items = new List<RecipeItem>");
        sb.AppendLine("                {");
        foreach (var ing in r.Ingredients)
        {
            if (ing.Mode == "specific")
                sb.AppendLine($"                    new RecipeItem({F(ing.MinimumCondition)}f) {{ specificId = \"{Escape(ing.Id)}\", isLiquid = {B(ing.IsLiquid)}, destroyItem = {B(ing.DestroyItem)} }},");
            else
                sb.AppendLine($"                    new RecipeItem({F(ing.MinimumCondition)}f) {{ quality = new CraftingQuality(\"{Escape(ing.Id)}\", {F(ing.Amount)}f), isLiquid = {B(ing.IsLiquid)}, destroyItem = {B(ing.DestroyItem)} }},");
        }
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine();
        return sb.ToString();
    }

    // ── custom status effects ───────────────────────────────────
    public static string EmitStatuses(Blueprint bp, List<StatusEntry> statuses)
    {
        var sb = new StringBuilder();
        var ns = SafeIdent(bp.Mod.RootNamespace);
        var guid = bp.Mod.Guid;
        sb.AppendLine("// AUTO-GENERATED by CuBlocky. Custom status effects.");
        sb.AppendLine("// Relies on CUCoreLib status storage + MoodleRegistry moodle display.");
        sb.AppendLine("using CUCoreLib.Data;");
        sb.AppendLine("using CUCoreLib.Helpers;");
        sb.AppendLine("using CUCoreLib.Registries;");
        sb.AppendLine("using HarmonyLib;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    // Custom BodyStatus classes: Level = current strength, RemainingSeconds = countdown.");
        sb.AppendLine("    // CUCoreLib auto-saves/syncs these via ConditionalWeakTable (StatusRegistry).");
        foreach (var st in statuses)
        {
            var cls = StatusClassName(st.Id);
            sb.AppendLine();
            sb.AppendLine($"    [StatusOptions(Key = \"{Escape(guid)}.{Escape(st.Id)}\", SaveEnabled = true)]");
            sb.AppendLine($"    public sealed class {cls} : BodyStatus");
            sb.AppendLine("    {");
            sb.AppendLine("        public float Level;");
            sb.AppendLine("        public float RemainingSeconds;");
            sb.AppendLine("    }");
        }
        sb.AppendLine();
        sb.AppendLine("    public static class StatusEffectsPatches");
        sb.AppendLine("    {");
        sb.AppendLine("        // Intensity from type: debuff = warning tiers (0-3), buff = positive tiers (4-6).");
        foreach (var st in statuses)
        {
            var cls = StatusClassName(st.Id);
            var intensity = st.Type == "buff" ? "5" : "2";
            var iconExpr = ResolveStatusIconExpr(st, bp);
            sb.AppendLine();
            sb.AppendLine($"        [HarmonyPatch(typeof(Body), \"Update\")]");
            sb.AppendLine("        [HarmonyPostfix]");
            sb.AppendLine($"        public static void Tick_{cls}(Body __instance)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var st = __instance.GetStatus<{cls}>();");
            sb.AppendLine("            if (st.Level > 0f)");
            sb.AppendLine("            {");
            sb.AppendLine("                st.RemainingSeconds -= Time.deltaTime;");
            sb.AppendLine("                if (st.RemainingSeconds < 0f)");
            sb.AppendLine("                {");
            sb.AppendLine("                    st.Level = 0f;");
            sb.AppendLine("                    st.RemainingSeconds = 0f;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            if (st.Level > 0f && st.RemainingSeconds > 0f)");
            sb.AppendLine("            {");
            sb.AppendLine($"                MoodleRegistry.AddMoodle({intensity}, {iconExpr}, \"{Escape(st.FullName)}\", \"{Escape(st.Description)}\", important: true, key: \"{Escape(guid)}.{Escape(st.Id)}\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        // Placeholder icon helper if any status has no sprite
        if (statuses.Any(st => string.IsNullOrEmpty(ResolveSpriteName(st.SpriteAssetId, bp))))
        {
            sb.AppendLine();
            sb.AppendLine("        private static Sprite StatusPlaceholderSprite(Color color)");
            sb.AppendLine("        {");
            sb.AppendLine("            int size = 16;");
            sb.AppendLine("            var tex = new Texture2D(size, size, TextureFormat.RGBA32, false);");
            sb.AppendLine("            var pixels = new Color[size * size];");
            sb.AppendLine("            for (int i = 0; i < pixels.Length; i++) pixels[i] = color;");
            sb.AppendLine("            tex.SetPixels(pixels);");
            sb.AppendLine("            tex.Apply();");
            sb.AppendLine("            return Sprite.Create(tex, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), 16f);");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string StatusClassName(string id)
    {
        return "Status_" + SafeIdent(id);
    }

    private static string ResolveStatusIconExpr(StatusEntry st, Blueprint bp)
    {
        var spriteName = ResolveSpriteName(st.SpriteAssetId, bp);
        if (!string.IsNullOrEmpty(spriteName))
            return $"LoadSprite(\"{Escape(CleanSpriteName(spriteName))}\")";
        // No icon: colored placeholder by type (green buff / red debuff)
        var color = st.Type == "buff" ? "new Color(0.3f, 0.8f, 0.4f)" : "new Color(0.9f, 0.3f, 0.3f)";
        return $"StatusPlaceholderSprite({color})";
    }

    // ── helpers ───────────────────────────────────────────────────
    private static string ResolveSpriteName(string assetId, Blueprint bp)
    {
        if (!string.IsNullOrEmpty(assetId))
        {
            // Try to find in bp.Assets first
            var asset = bp.Assets.FirstOrDefault(a => a.Id == assetId);
            if (asset != null) return asset.Name;
            // If not in Assets, treat the asset ID as the filename directly
            return assetId;
        }
        return "";
    }

    private static string F(float v) => v.ToString("0.###", CultureInfo.InvariantCulture);
    private static string B(bool v) => v ? "true" : "false";
    private static string Cap(string s) => string.IsNullOrEmpty(s) ? "Tools" : char.ToUpperInvariant(s[0]) + s.Substring(1).ToLowerInvariant();
    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", " ").Replace("\n", " ");
    private static string CleanSpriteName(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        s = s.Trim().Trim('"', '\'');
        return s;
    }
    private static string SafeIdent(string s)
    {
        var sb = new StringBuilder();
        foreach (var c in s)
            if (char.IsLetterOrDigit(c)) sb.Append(c); else sb.Append('_');
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, "M");
        return sb.ToString();
    }

    private static string EmitBuilding(BuildingEntry b)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"            BuildingEntityRegistry.Register(\"{Escape(b.Id)}\", new CustomBuildingEntityDefinition {{");
        sb.AppendLine($"                Name = \"{Escape(b.Name)}\",");
        sb.AppendLine($"                Description = \"{Escape(b.Desc)}\"");
        sb.AppendLine("            });");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EmitTile(TileEntry t)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"            TileRegistry.Register(\"{Escape(t.Id)}\", new CustomTileDefinition {{");
        sb.AppendLine($"                Name = \"{Escape(t.Name)}\"");
        sb.AppendLine("            });");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EmitLocale(LocaleEntry l)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"            LocaleRegistry.Register(\"{Escape(l.Type)}\", \"{Escape(l.Id)}\", \"{Escape(l.Zh)}\");");
        sb.AppendLine($"            LocaleRegistry.Register(\"{Escape(l.Type)}\", \"{Escape(l.Id)}dsc\", \"{Escape(l.En)}\");");
        sb.AppendLine();
        return sb.ToString();
    }
}
