using System.Globalization;
using System.Text;
using CuBlocky.Server.Models;

namespace CuBlocky.Server.Compiler;

// Emits C# registration calls from form-driven content + block behavior.
// Targets .NET Framework 4.7.2 (BepInEx 5 / Unity / Mono).
public static class CodeEmitter
{
    public static string EmitRegisterContent(Blueprint bp, List<ItemEntry> extraItems = null, List<RecipeEntry> extraRecipes = null, List<BuildingEntry> buildings = null, List<TileEntry> tiles = null, List<LocaleEntry> locales = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by CuBlocky. Do not edit by hand; edit the .cbp and recompile.");
        sb.AppendLine("// Depends on CUCoreLib (net.cucorelib). Place CUCoreLib.dll in BepInEx/plugins/.");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CUCoreLib.Helpers;");
        sb.AppendLine("using CUCoreLib.Registries;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine($"namespace {SafeIdent(bp.Mod.RootNamespace)}");
        sb.AppendLine("{");
        sb.AppendLine("    public static class RegisterContent");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void RegisterAll()");
        sb.AppendLine("        {");

        var allItems = new List<ItemEntry>(bp.Items);
        if (extraItems != null) allItems.AddRange(extraItems);
        foreach (var item in allItems)
            sb.Append(EmitItem(item, bp));

        var allRecipes = new List<RecipeEntry>(bp.Recipes);
        if (extraRecipes != null) allRecipes.AddRange(extraRecipes);
        foreach (var recipe in allRecipes)
            sb.Append(EmitRecipe(recipe));

        if (buildings != null)
        {
            foreach (var b in buildings)
                sb.Append(EmitBuilding(b));
        }

        if (tiles != null)
        {
            foreach (var t in tiles)
                sb.Append(EmitTile(t));
        }

        if (locales != null)
        {
            foreach (var l in locales)
                sb.Append(EmitLocale(l));
        }

        sb.AppendLine("        }");

        // Emit placeholder sprite helper if any item has no sprite
        var allItemsList = new List<ItemEntry>(bp.Items);
        if (extraItems != null) allItemsList.AddRange(extraItems);
        if (allItemsList.Any(it => string.IsNullOrEmpty(it.SpriteAssetId)))
            sb.AppendLine(EmitPlaceholderSpriteHelper());

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitItem(ItemEntry it, Blueprint bp)
    {
        var sb = new StringBuilder();
        sb.AppendLine("            // Item: " + it.Id);
        sb.Append($"            ItemRegistry.Register(");
        sb.Append($"\"{Escape(it.Id)}\", ");
        sb.AppendLine("new ItemInfo");
        sb.AppendLine("            {");
        sb.AppendLine($"                fullName = \"{Escape(it.FullName)}\",");
        sb.AppendLine($"                description = \"{Escape(it.Description)}\",");
        sb.AppendLine($"                category = \"{Escape(it.Category)}\",");
        sb.AppendLine($"                weight = {F(it.Weight)}f,");
        sb.AppendLine($"                value = {it.Value},");
        if (it.Usable || !string.IsNullOrEmpty(it.UseAction))
            sb.AppendLine($"                usable = true,");
        if (it.UsableOnLimb || !string.IsNullOrEmpty(it.UseLimbAction))
            sb.AppendLine($"                usableOnLimb = true,");
        sb.AppendLine($"                decayMinutes = {F(it.DecayMinutes)}f,");
        if (!string.IsNullOrEmpty(it.Tags))
            sb.AppendLine($"                tags = \"{Escape(it.Tags)}\",");
        sb.AppendLine($"                rec = new Recognition({it.Recognition}),");

        // useAction from Blockly-generated C# code
        if (!string.IsNullOrEmpty(it.UseAction))
        {
            sb.AppendLine("                useAction = (body, item) =>");
            sb.AppendLine("                {");
            // Replace {body} and {item} placeholders with actual parameter names
            var code = it.UseAction
                .Replace("{body}", "body")
                .Replace("{item}", "item")
                .Replace("{limb}", "limb");
            foreach (var line in code.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                if (!string.IsNullOrWhiteSpace(trimmed))
                    sb.AppendLine("                    " + trimmed);
            }
            sb.AppendLine("                },");
        }

        // useLimbAction from Blockly-generated C# code
        if (!string.IsNullOrEmpty(it.UseLimbAction))
        {
            sb.AppendLine("                useLimbAction = (limb, item) =>");
            sb.AppendLine("                {");
            var code = it.UseLimbAction
                .Replace("{body}", "limb")
                .Replace("{item}", "item")
                .Replace("{limb}", "limb");
            foreach (var line in code.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                if (!string.IsNullOrWhiteSpace(trimmed))
                    sb.AppendLine("                    " + trimmed);
            }
            sb.AppendLine("                },");
        }

        sb.AppendLine("            }");
        // sprite - load from embedded resource or generate placeholder
        if (!string.IsNullOrEmpty(it.SpriteAssetId))
        {
            var spriteName = ResolveSpriteName(it, bp);
            sb.AppendLine($"            , AssetLoader.LoadEmbeddedSprite(\"{Escape(spriteName)}\")");
        }
        else
        {
            sb.AppendLine($"            , CuBlockyPlaceholderSprite(\"{Escape(it.Id)}\")");
        }
        if (it.SpawnFrequency != 1)
            sb.AppendLine($"            , {it.SpawnFrequency}");
        sb.AppendLine("            );");
        sb.AppendLine();
        return sb.ToString();
    }

    /// <summary>
    /// Emits a helper method that generates a colored placeholder sprite at runtime.
    /// Called once per RegisterContent class.
    /// </summary>
    public static string EmitPlaceholderSpriteHelper()
    {
        return @"
        private static UnityEngine.Sprite CuBlockyPlaceholderSprite(string itemId)
        {
            int size = 16;
            var tex = new UnityEngine.Texture2D(size, size, UnityEngine.TextureFormat.RGBA32, false);
            var pixels = new UnityEngine.Color[size * size];
            // Magenta background
            for (int i = 0; i < pixels.Length; i++) pixels[i] = new UnityEngine.Color(1f, 0f, 1f, 1f);
            // Dark border
            for (int x = 0; x < size; x++) { pixels[x] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); pixels[(size - 1) * size + x] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); }
            for (int y = 0; y < size; y++) { pixels[y * size] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); pixels[y * size + size - 1] = new UnityEngine.Color(0.2f, 0f, 0.2f, 1f); }
            // Small cross in center
            int cx = size / 2, cy = size / 2;
            pixels[cy * size + cx] = UnityEngine.Color.white;
            pixels[cy * size + cx - 1] = UnityEngine.Color.white;
            pixels[cy * size + cx + 1] = UnityEngine.Color.white;
            pixels[(cy - 1) * size + cx] = UnityEngine.Color.white;
            pixels[(cy + 1) * size + cx] = UnityEngine.Color.white;
            tex.SetPixels(pixels);
            tex.Apply();
            return UnityEngine.Sprite.Create(tex, new UnityEngine.Rect(0, 0, size, size), new UnityEngine.Vector2(0.5f, 0.5f), 16f);
        }
";
    }

    public static string EmitRecipe(RecipeEntry r)
    {
        var sb = new StringBuilder();
        sb.AppendLine("            // Recipe -> " + r.ResultId);
        sb.AppendLine("            RecipeRegistry.Register(new Recipe");
        sb.AppendLine("            {");
        sb.AppendLine($"                INT = {r.IntRequirement},");
        sb.AppendLine($"                category = Recipes.RecipeCategory.{Cap(r.Category)},");
        sb.AppendLine("                result = new RecipeResult");
        sb.AppendLine("                {");
        sb.AppendLine($"                    id = \"{Escape(r.ResultId)}\",");
        sb.AppendLine($"                    amount = {r.ResultAmount},");
        sb.AppendLine($"                    isLiquid = {B(r.IsLiquidResult)},");
        sb.AppendLine($"                    resultCondition = {F(r.ResultCondition)}f,");
        sb.AppendLine("                },");
        sb.AppendLine("                items = new List<RecipeItem>");
        sb.AppendLine("                {");
        foreach (var ing in r.Ingredients)
        {
            if (ing.Mode == "specific")
                sb.AppendLine($"                    new RecipeItem({F(ing.Amount)}f) {{ specificId = \"{Escape(ing.Id)}\", isLiquid = {B(ing.IsLiquid)}, destroyItem = {B(ing.DestroyItem)} }},");
            else
                sb.AppendLine($"                    new RecipeItem({F(ing.Amount)}f) {{ quality = new CraftingQuality(\"{Escape(ing.Id)}\", {F(ing.Amount)}f), isLiquid = {B(ing.IsLiquid)}, destroyItem = {B(ing.DestroyItem)} }},");
        }
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine();
        return sb.ToString();
    }

    // ── helpers ───────────────────────────────────────────────────
    private static string ResolveSpriteName(ItemEntry it, Blueprint bp)
    {
        if (!string.IsNullOrEmpty(it.SpriteAssetId))
        {
            // Try to find in bp.Assets first
            var asset = bp.Assets.FirstOrDefault(a => a.Id == it.SpriteAssetId);
            if (asset != null) return asset.Name;
            // If not in Assets, treat SpriteAssetId as the filename directly
            return it.SpriteAssetId;
        }
        return it.Id + ".png";
    }

    private static string F(float v) => v.ToString("0.###", CultureInfo.InvariantCulture);
    private static string B(bool v) => v ? "true" : "false";
    private static string Cap(string s) => string.IsNullOrEmpty(s) ? "Tools" : char.ToUpperInvariant(s[0]) + s.Substring(1).ToLowerInvariant();
    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", " ").Replace("\n", " ");
    private static string SafeIdent(string s)
    {
        var sb = new StringBuilder();
        foreach (var c in s)
            if (char.IsLetterOrDigit(c)) sb.Append(c); else sb.Append('_');
        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, "M");
        return sb.ToString();
    }

    private static string EmitBuilding(BuildingEntry b)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"            BuildingEntityRegistry.Register(\"{Escape(b.Id)}\", new CustomBuildingEntityDefinition {{");
        sb.AppendLine($"                Name = \"{Escape(b.Name)}\",");
        sb.AppendLine($"                Description = \"{Escape(b.Desc)}\",");
        sb.AppendLine($"                Health = {b.Health}f,");
        sb.AppendLine($"                Placement = BuildingPlacementType.{b.Placement}");
        sb.AppendLine("            });");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EmitTile(TileEntry t)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"            TileRegistry.Register(\"{Escape(t.Id)}\", new CustomTileDefinition {{");
        sb.AppendLine($"                Name = \"{Escape(t.Name)}\",");
        sb.AppendLine($"                Health = {t.Health}f,");
        sb.AppendLine($"                ColliderType = TileColliderType.{t.Collider},");
        sb.AppendLine($"                GenerationStyle = TileGenerationStyle.{t.GenStyle}");
        sb.AppendLine("            });");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EmitLocale(LocaleEntry l)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"            LocaleRegistry.Register(\"{Escape(l.Type)}\", \"{Escape(l.Id)}\", \"{Escape(l.Zh)}\");");
        sb.AppendLine($"            LocaleRegistry.Register(\"{Escape(l.Type)}\", \"{Escape(l.Id)}dsc\", \"{Escape(l.En)}\");");
        sb.AppendLine();
        return sb.ToString();
    }
}
