export type SplashEntry = [string, string, string]; // [zh, en, ru]

const SPLASH_TEXTS: SplashEntry[] = [
  ['Also try Terraria!', 'Also try Terraria!', 'Также попробуйте Terraria!'],
  ['100% 纯 C#!', '100% pure C#!', '100% чистый C#!'],
  ['更多积木了!', 'Now with more blocks!', 'Теперь с ещё блоками!'],
  ['Roguelike!', 'Roguelike!', 'Рогалик!'],
  ['洞穴探险既视感!', 'Spelunky vibes!', 'Настроение Спеланки!'],
  ['程序化生成!', 'Procedurally generated!', 'Процедурная генерация!'],
  ['不含任何真实伤亡!', 'Contains no actual casualties!', 'Без реальных жертв!'],
  ['用 BepInEx 做的!', 'Made with BepInEx!', 'Сделано в BepInEx!'],
  ['Harmony 补丁冲冲冲!', 'Harmony patches go brrr!', 'Harmony патчи летят!'],
  ['Blockly 好玩!', 'Blockly is fun!', 'Blockly — это весело!'],
  ['Unity 什么时候?', 'Unity when?', 'Unity когда?'],
  ['开源!', 'Open source!', 'Открытый код!'],
  ['无 bug 保证!*', 'Bug-free guarantee!*', 'Гарантия без багов!*'],
  ['*此保证无效', '*Offer not valid', '*Предложение не действительно'],
  ['出去摸摸草!', 'Touch grass!', 'Потрогай траву!'],
  ['Hello world!', 'Hello world!', 'Привет мир!'],
  ['编译通过了!', 'It compiles!', 'Компилируется!'],
  ['直接发!', 'Ship it!', 'Отправляй!'],
  ['这不是 bug，是功能!', "It's not a bug, it's a feature!", 'Это не баг, это фича!'],
  ['试过关机重启吗?', 'Have you tried turning it off and on again?', 'Вы пробовали выключить и включить?'],
  ['我机器上能跑!', 'Works on my machine!', 'На моей машине работает!'],
  ['蛋糕是骗局!', 'The cake is a lie!', 'Торт — ложь!'],
  ['这段文字是黄色的!', 'This text is yellow!', 'Этот текст жёлтый!'],
  ['哇!', 'Wow!', 'Вау!'],
  ['好闪屏!', 'Such splash!', 'Какая вспышка!'],
  ['好随机!', 'Much random!', 'Очень случайно!'],
  ['好 MC!', 'Very Minecraft!', 'Очень Minecraft!'],
  ['好程序化!', 'So procedural!', 'Очень процедурно!'],
  ['太棒了!', 'Amazing!', 'Невероятно!'],
  ['难以置信!', 'Incredible!', 'Неправдоподобно!'],
  ['技术上正确就是最好的正确!', 'Technically correct is the best kind of correct!', 'Технически верно — лучшая верность!'],
  ['404: 标语没找到', '404: Splash text not found', '404: Текст вспышки не найден'],
  ['加载中...', 'Loading...', 'Загрузка...'],
  ['请稍候...', 'Please wait...', 'Подождите...'],
  ['错误: 成功!', 'Error: Success!', 'Ошибка: Успех!'],
  ['别碰禁止的代码!', 'Do not touch the forbidden code!', 'Не трогай запретный код!'],
  ['Ctrl+C, Ctrl+V', 'Ctrl+C, Ctrl+V', 'Ctrl+C, Ctrl+V'],
  ['git commit -m "修好了"', 'git commit -m "fixed everything"', 'git commit -m "всё исправлено"'],
  ['npm install coffee', 'npm install coffee', 'npm install кофе'],
  ['StackOverflow: 真正的 MVP', 'Stack overflow: The real MVP', 'StackOverflow: Настоящий MVP'],
  ['代码即文档', 'The code is the documentation', 'Код — это документация'],
  ['TODO: 写更好的 TODO', 'TODO: Write better TODOs', 'TODO: Написать лучшие TODO'],
  ['能跑就别动!', "It works, don't touch it!", 'Работает — не трогай!'],
  ['魔法数字: 启动!', 'Magic numbers: Engaged!', 'Магические числа: Активированы!'],
  ['明天重构...', 'Refactoring tomorrow...', 'Рефакторинг завтра...'],
  ['这很合理 🔥', 'This is fine 🔥', 'Всё нормально 🔥'],
  ['零 bug（我们知道的）', 'Zero bugs found (that we know of)', 'Ноль багов (известных нам)'],
  ['Ctrl+Z 是我最好的朋友', 'Ctrl+Z is my best friend', 'Ctrl+Z — мой лучший друг'],
  ['像没人看着一样写代码!', 'Code like nobody is watching!', 'Кодь так, будто никто не смотрит!'],
  ['睡前再提交一次...', 'One more commit before bed...', 'Ещё один коммит перед сном...'],
];

export default SPLASH_TEXTS;
