export type SplashEntry = [string, string, string]; // [zh, en, ru]

const SPLASH_TEXTS: SplashEntry[] = [
  ['也去玩泰拉瑞亚吧!', 'Also try Terraria!', 'Также попробуйте Terraria!'],
  ['更多积木了!', 'Now with more blocks!', 'Теперь с ещё блоками!'],
  ['程序化生成!', 'Procedurally generated!', 'Процедурная генерация!'],
  ['不含任何真实伤亡!', 'Contains no actual casualties!', 'Без реальных жертв!'],
  ['Casualties Unknown 模组!', 'Casualties Unknown modding!', 'Моддинг Casualties Unknown!'],
  ['为 CU 做模组!', 'Modding for CU!', 'Моды для CU!'],

  ['出去摸摸草!', 'Touch grass!', 'Потрогай траву!'],
  ['这段文字是黄色的!', 'This text is yellow!', 'Этот текст жёлтый!'],
  ['哇!', 'Wow!', 'Вау!'],
  ['非常随机!', 'Much random!', 'Очень случайно!'],
  ['非常 MC!', 'Very Minecraft!', 'Очень Minecraft!'],
  ['太棒了!', 'Amazing!', 'Невероятно!'],
  ['难以置信!', 'Incredible!', 'Неправдоподобно!'],
  ['这很合理 🔥', 'This is fine 🔥', 'Всё нормально 🔥'],
  ['零 bug（我们知道的）', 'Zero bugs found (that we know of)', 'Ноль багов (известных нам)'],
  ['睡前再玩一次...', 'One more run before bed...', 'Ещё один забег перед сном...'],
  ['刚想保存游戏就断电了', 'Power outage right before saving', 'Свет погас как раз перед сохранением'],
  ['为什么地板上有水?', 'Why is the floor wet?', 'Почему пол мокрый?'],
  ['猫坐在键盘上', 'Cat on keyboard', 'Кот на клавиатуре'],
  ['咖啡是生命之水', 'Coffee is life juice', 'Кофе — сок жизни'],
  ['周一又来了...', 'Monday again...', 'Снова понедельник...'],
  ['五点下班倒计时', 'Counting down to 5 PM', 'Обратный отсчёт до 17:00'],

  ['Hello world!', 'Hello world!', 'Привет мир!'],
  ['编译通过了!', 'It compiles!', 'Компилируется!'],
  ['直接发!', 'Ship it!', 'Отправляй!'],
  ['这只是特性!', "It's not a bug, it's a feature!", 'Это не баг, это фича!'],
  ['试过关机重启吗?', 'Have you tried turning it off and on again?', 'Вы пробовали выключить и включить?'],
  ['我机器上能跑!', 'Works on my machine!', 'На моей машине работает!'],
  ['蛋糕是骗局!', 'The cake is a lie!', 'Торт — ложь!'],
  ['技术上正确就是最好的正确!', 'Technically correct is the best kind of correct!', 'Технически верно — лучшая верность!'],
  ['404: Splash text not found', '404: Splash text not found', '404: Текст вспышки не найден'],
  ['加载中...', 'Loading...', 'Загрузка...'],
  ['错误: 成功!', 'Error: Success!', 'Ошибка: Успех!'],
  ['git commit -m "修好了所有BUG"', 'git commit -m "fixed everything"', 'git commit -m "всё исправлено"'],
  ['npm install coffee', 'npm install coffee', 'npm install кофе'],
  ['StackOverflow: 真正的 MVP', 'Stack Overflow: The real MVP', 'Stack Overflow: Настоящий MVP'],
  ['能跑就别动!', "It works, don't touch it!", 'Работает — не трогай!'],
  ['明天重构...', 'Refactoring tomorrow...', 'Рефакторинг завтра...'],
  ['Ctrl+Z 拯救世界', 'Ctrl+Z saves the world', 'Ctrl+Z спасает мир'],
  ['睡前再提交一次...', 'One more commit before bed...', 'Ещё один коммит перед сном...'],

  ['让模组制作像搭积木一样简单', 'Modding made block-simple', 'Моддинг простой как кубики'],
  ['Blockly 积木不只是给小孩玩的!', 'Blockly blocks aren\'t just for kids!', 'Блоки Blockly не только для детей!'],
  ['拖拽生成 C# 代码!', 'Drag blocks, get C#!', 'Перетаскивай блоки — получай C#!'],
  ['无需写代码也能做模组!', 'Make mods without writing code!', 'Создавай моды без кода!'],
  ['所见即所得!', 'WYSIWYG!', 'что видишь, то и есть!'],
  ['一键导出 BepInEx 插件!', 'One-click BepInEx plugin export!', 'Экспорт BepInEx плагина за клик!'],
  ['感谢 BepInEx 团队!', 'Thanks BepInEx team!', 'Спасибо команде BepInEx!'],
  ['感谢 0Harmony!', 'Thanks 0Harmony!', 'Спасибо 0Harmony!'],
  ['Orsoniks 制作了很棒的游戏!', 'Orsoniks made a great game!', 'Orsoniks сделал крутую игру!'],
  ['别告诉他们这段标语在中文下与其他语言不一致', 'This is an easter egg 🥚', 'Это пасхалка 🥚'],
  ['按 F 致敬', 'Press F to pay respects', 'Нажми F чтобы почтить память'],
  ['按 R 重新开始', 'Press R to restart', 'Нажми R чтобы начать заново'],
  ['Shift+点击 = 快速放置', 'Shift+click = quick place', 'Shift+клик = быстрая установка'],
  ['Alt+点击 = 复制方块', 'Alt+click = copy block', 'Alt+клик = копировать блок'],
  ['支持中英俄三语!', 'Supports CN/EN/RU!', 'Поддержка CN/EN/RU!'],
  ['夜间构建也能玩!', 'Night builds are playable too!', 'Ночные сборки тоже играбельны!'],
  ['由 ouse114514 开发', 'Developed by ouse114514', 'Разработано ouse114514'],
];

export default SPLASH_TEXTS;